### ISSUE TITLE
OSDF cache inconsistencies between branches

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs-contrib/config-repo#185]
The master branch is expected to have a superset of the other branches.  The domain.d/osgstorage.org.conf and osgstorage-auth.conf files in the master branch have sections for servers in osg and servers not in osg.  So I expect to be able to do a git diff on those files between branches, for example from the master branch
```
git diff osg etc/cvmfs/domain.d/osgstorage.org.conf
```
and then the list of external servers in the osg section should be identical between the two branches.  That is not the case, there are a lot of differences.  Likewise for egi and the section of servers not used by osg.  Please make them consistent.  I expect there to be some missing servers in the egi branch from the osg section and for the egi section to be completely missing in the osg branch.  The default branch should be just like egi in osgstorage.org.conf.

@biozit

**Comment by biozit** [comment]
sure!

**Comment by DrDaveD** [comment]
Fixed in #224
