### ISSUE TITLE
Inconsistencies between osg and egi branches in lists of OSDF servers

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs-contrib/config-repo#192]
In the egi branch I should be able to do `git diff osg domain.d/osgstorage.org.conf` and `git diff osg osgstorage-auth.conf` and see only difference lines beginning with `-` in the North America section of `subset of authenticated OSDF caches used by OSG`, and all the lines after `extra authenticated OSDF caches not used by OSG` should begin with `+`.   There are a few cases where that is not so.  Please make it consistent.

In addition, `git diff default domain.d/osgstorage.org.conf` should show no difference of servers between egi and default branches.

**Comment by DrDaveD** [comment]
In addition, doing `git diff master domain.d/osgstorage.org.conf` and `git diff master osgstorage-auth.conf` should show no differences in the lines after `extra authenticated OSDF caches not used by OSG`. 

Currently this is not the case, because `cf-ac-uk-cache.nationalresearchplatform.org` is in the master branch but not in the egi branch for both files.

Beyond that, the comparison between osg and egi now looks good, but the default branch's `domain.d/osgstorage.org.conf` still has a lot of differences that need to be brought in sync.

**Comment by DrDaveD** [comment]
Also, from the osg branch doing `git diff master domain.d/osgstorage.org.conf` and `git diff master osgstorage-auth.conf` should show no differences in the section `OSDF caches used by OSG` and the lines after `extra OSDF caches not used by OSG` should be marked with `-` only.

Currently there are two servers in the OSG section in the master branch that are not in the osg branch in both files: `mghpcc-cache.nationalresearchplatform.org` and `sdsc-cache.nationalresearchplatform.org`.  sdsc-cache was removed temporarily in #229.  Perhaps it is time to add it back?  If not, it should get removed from the master branch.  Or, instead of deleting it, probably it would be better to comment it out with a dated note that it is temporary.  Likewise mghpcc-cache and #235.

**Comment by DrDaveD** [comment]
Now that #241 is finished, please sync up the default branch with the egi branch

**Comment by DrDaveD** [comment]
Oh and `cf-ac-uk-cache.nationalresearchplatform.org` is still in the master branch's domain.d/osgstorage.org.conf but not in egi.  Shouldn't it be there?   It is in osgstorage-auth.conf in both branches.

**Comment by DrDaveD** [comment]
> Now that #241 is finished, please sync up the default branch with the egi branch

> Oh and `cf-ac-uk-cache.nationalresearchplatform.org` is still in the master branch's domain.d/osgstorage.org.conf but not in egi. Shouldn't it be there? It is in osgstorage-auth.conf in both branches.

@biozit

**Comment by biozit** [comment]
I will add it back to EGI.

*--Fábio Andrijauskas*
