### ISSUE TITLE
Add KAGRA OSDF Cache to CVMFS configurations

### ISSUE THREAD

**Issue by duncanmmacleod** [cvmfs-contrib/config-repo#247]
A new OSDF cache has been configured (and [registered in OSG topology](https://github.com/opensciencegrid/topology/blob/fd01529be6263f45209365d8dd4b2b2ec54c683e/topology/The%20University%20of%20Tokyo/Kashiwa/KAGRA-OSDF.yaml#L28-L46)) for the University of Tokyo (supporting the KAGRA observatory).
 
Can this please be added to the CVMFS configurations for repositories under the `storage.igwn.org` domain?

cc @biozit @xkzl

**Comment by biozit** [comment]
sure, finishing the test

**Comment by xkzl** [comment]
I just checked in our computers, I think the configuration is fixed. Can you confirm @biozit ?

**Comment by biozit** [comment]
Yes,  the cache looks good!

https://github.com/cvmfs-contrib/config-repo/pull/250
https://github.com/cvmfs-contrib/config-repo/pull/249
https://github.com/cvmfs-contrib/config-repo/pull/248

**Comment by biozit** [comment]
@xkzl Are you running both OSDF cache instances (auth and non-auth)?

**Comment by xkzl** [comment]
@biozit only the authenticated one

**Comment by duncanmmacleod** [comment]
I can confirm that the KAGRA OSDF cache is now being seen by CVMFS via the EGI configuration, so am happy to close this out. Thanks @biozit.
