### ISSUE TITLE
Add EESSI configuration

### ISSUE THREAD

**Issue by bedroge** [cvmfs-contrib/config-repo#54]
Hi @DrDaveD,

As you suggested on the CVMFS forum (https://cernvm-forum.cern.ch/t/best-practices-for-client-configuration-packages-without-config-repo/47/9), I'm opening this issue as a request to include the EESSI configuration in one of the cvmfs-config repos. (EGI?).

The latest configuration packages (rpm/deb/tar) for the EESSI repositories can be found at:
https://github.com/EESSI/filesystem-layer/releases/tag/v0.3.0
Note that it currently still includes some more keys, partly due to legacy reasons (old cvmfs-config repo) and because of an issue with the Ansible role that we use to configure our servers. However, for this purpose it should be sufficient to only include the `pilot.eessi-hpc.org.pub` key (and perhaps rename it to `eessi-hpc.org.pub`?). For future repos, we will make use of the master/pub key of this repo.

If you need any more information, please let me know!

**Comment by DrDaveD** [comment]
I'm not sure exactly how the [rpm](https://github.com/EESSI/filesystem-layer/releases/download/v0.3.0/cvmfs-config-eessi-0.3.0-1.noarch.rpm) is generated, but downloading it and running it through rpm2cpio was the easiest way I found to get `domain.d/eessi-hpc.org.con`f and `keys/eessi-hpc.org/pilot.eessi-hpc.org.pub`.

**Comment by jblomer** [comment]
As discussed yesterday, I'd like to add it to the default repo.

**Comment by DrDaveD** [comment]
Ok as discussed yesterday, when ready Bob will submit it as a pull request against the default branch.

**Comment by boegel** [comment]
We briefly discussed this during our EESSI monthly meeting yesterday.

@bedroge will look into creating a new master key and adopt the use of yubikeys to store it safely. Once that is done, we will look into the pull request to add the new public key and corresponding configuration to the `default` branch in this repo.

**Comment by boegel** [comment]
done, see #206 + #207, so can be closed
